package com.ics.pos.restaurant.icsrestaurant.model;

import java.time.LocalDate;


public class ClrbalanceBean {

    private String rIndex;
    private String rTable;
    private LocalDate rDate;
    private String rTime;
    private String macno;
    private String cashier;
    private String rEmp;
    private String rPlucode;
    private String rPname;
    private String rUnit;
    private String rGroup;
    private String rStatus;
    private String rNormal;
    private String rDiscount;
    private String rService;
    private String rStock;
    private String rSet;
    private String rVat;
    private String rType;
    private String rEtd;
    private Float rQuan;
    private Float rPrice;
    private Float rTotal;
    private String rPrtype;
    private String rPrcode;
    private Float rPrdisc;
    private Float rPrbath;
    private Float rPramt;
    private Float rDiscbath;
    private String rPrcutype;
    private Float rPrcuquan;
    private Float rPrcuamt;
    private Float rRedule;
    private String rKic;
    private String rKicprint;
    private String rVoid;
    private String rVoiduser;
    private String rVoidtime;
    private String rOpt1;
    private String rOpt2;
    private String rOpt3;
    private String rOpt4;
    private String rOpt5;
    private String rOpt6;
    private String rOpt7;
    private String rOpt8;
    private String rOpt9;
    private String rPrcucode;
    private String rServe;
    private String rPrintok;
    private String rKicok;
    private String stkcode;
    private String posstk;
    private String rPrchktype;
    private Float rPrquan;
    private String rPrsubtype;
    private String rPrsubcode;
    private Float rPrsubquan;
    private Float rPrsubdisc;
    private Float rPrsubbath;
    private Float rPrsubamt;
    private Float rPrsubadj;
    private Float rPrcudisc;
    private Float rPrcubath;
    private Float rPrcuadj;
    private Float rQuancandisc;
    private String rOrder;
    private Integer rPitemno;
    private Integer rPkicque;
    private String rMemsum;
}
