package com.ics.pos.restaurant.icsrestaurant.model;

import java.time.LocalDate;


public class TemptSaleCopyBean {

    private String rIndex;
    private String rRefno;
    private String rTable;
    private LocalDate rDate;
    private String rTime;
    private String macno;
    private String cashier;
    private String rEmp;
    private String rPlucode;
    private String rPname;
    private String rUnit;
    private String rGroup;
    private String rStatus;
    private String rNormal;
    private String rDiscount;
    private String rService;
    private String rStock;
    private String rSet;
    private String rVat;
    private String rType;
    private String rEtd;
    private Float rQuan;
    private Float rPrice;
    private Float rTotal;
    private String rPrtype;
    private String rPrcode;
    private Float rPrdisc;
    private Float rPrbath;
    private Float rPramt;
    private String rPrcutype;
    private String rPrcucode;
    private Float rPrcuquan;
    private Float rPrcuamt;
    private Float rRedule;
    private Float rDiscbath;
    private Float rPradj;
    private Float rNettotal;
    private String rKic;
    private String rKicprint;
    private String rRefund;
    private String voidmsg;
    private String rVoid;
    private String rVoiduser;
    private String rVoidtime;
    private String stkcode;
    private String posstk;
    private Float rServiceamt;
    private String rPrchktype;
    private Float rPrquan;
    private String rPrsubtype;
    private String rPrsubcode;
    private Float rPrsubquan;
    private Float rPrsubdisc;
    private Float rPrsubbath;
    private Float rPrsubamt;
    private Float rPrsubadj;
    private Float rPrcudisc;
    private Float rPrcubath;
    private Float rPrcuadj;
    private String rPrchktype2;
    private Float rPrquan2;
    private String rPrtype2;
    private String rPrcode2;
    private Float rPrdisc2;
    private Float rPrbath2;
    private Float rPramt2;
    private Float rPradj2;
    private Integer rPitemno;
    private Integer rPkicque;
    private String rMoveitem;
    private String rMovefrom;
    private String rMoveuser;
    private String rMoveflag;
}
