package com.ics.pos.restaurant.icsrestaurant.model;


public class TranconfigBean {

    private String btype;
    private String hostname;
    private String username;
    private String password;
    private Integer port;
    private String saledatapath;
    private String stockdatapath;
    private String bordatapath;
    private String receivepath;
    private String bortobranpath;
    private String sendscardpath;
    private String borscardpath;
    private String receivescardpath;
    private String borrcardpath;
    private String borejpath;
    private String memhostname;
    private String memusername;
    private String mempassword;
    private Integer memport;
    private String memrecivepath;
    private String membortobranpath;
    private String gifthostname;
    private String giftusername;
    private String giftpassword;
    private Integer giftport;
    private String giftrecivepath;
    private String giftbortobranpath;
    private String rechostname;
    private String recusername;
    private String recpassword;
    private Integer recport;
    private String recrecivepath;
    private String recbortobranpath;
    private String chkftpactive;
    private String chksendtran;
    private String chksendinhand;
    private String aplocalpath;
    private String apborpath;
    private String mapaplocalpath;
    private String mapapborpath;
    private String chksendcsv;
    private Integer selectsendtype;
    private String mapsalesend;
    private String mapmonthstock;
    private String mapbordata;
    private String mapborej;
    private String mapreceivedata;
    private String mapbortobranch;
    private String mapscardsend;
    private String mapborscarddata;
    private String mapscardreceive;
    private String mapborscardtobranch;
    private String maporderserverpath;
    private String maporderlocalpath;
    private String orderlocalpath;
    private String orderserverpath;
    private String logfilepath;
}
